algoritmo "semnome"
// Função :
// Autor :
// Data : 03/02/2022
// Seção de Declarações 
var
   a, b, soma, diferenca: Real
inicio
      Escreval ("Digite o numero A ")
      Leia (a)
      Escreval ("Digite o numero B ")
      Leia (b)
      Soma <- (a + b)
      Escreval ("A Soma dos dois numeros sera de ", Soma)
      Diferenca <- (A - B)
      Escreva ("A diferenca entre os valores sera de ", diferenca)
fimalgoritmo
