algoritmo "semnome"
// Função :
// Autor :
// Data : 03/02/2022
// Seção de Declarações 
var
   A, B, SOMA : Inteiro
   Quadrado:Real
inicio
      Escreval ("Digite um numero A ")
      leia (a)
      Escreval ("Digite um numero B ")
      leia (B)
      Soma <- (a + b)
      Escreval ("A soma dos numero assim sera de ", soma)
      Quadrado <- (a^2) + (2*a*b) + (b^2)
      Escreval ("E a soma dos quadrados sera de ", quadrado)

fimalgoritmo
